### ISSUE TITLE
Fix same file saving bug

### ISSUE THREAD

**Issue by Yehonal** [AzerothShard/Character-Migration#1]
We should avoid that during chardump upload it is saved under storage/chardump.lua

it istead should be saved differentiating for account and suffixed by a numeric value ( because in some rare case the same account could upload two dumps from different tabs/browsers(?) 

for example:

chardump_michael_1.lua
chardump_john_1.lua

however it could be not strictly necessary since we've a delay of 120 secs between 2 porting and it should avoid this kind or problem.

**Comment by polaretto** [comment]
Fixed in 84209118b742b81b58891f405de5680a8bca5536
